export enum ENUM_CELEBRATION_STEPS {
    PRESENTATION = 'PRESENTATION',
    GIFT = 'GIFT',
    WINNER_INFO = 'WINNER_INFO',
    SPECIAL_MESSAGE_WITH_TITLE = 'SPECIAL_MESSAGE_WITH_TITLE',
    BALLOONS = 'BALLOONS',
    END = 'END'
}